switch.landing_blind_close_landing_blind:
  name: "LB Down"
  hidden: false
switch.landing_blind_stop_landing_blind:
  name: "LB Stop"
  hidden: false
switch.landing_blind_open_landing_blind:
  name: "LB Up"
  hidden: false
switch.loft_blind_close_loft_suite_blind:
  name: "RB Down"
  hidden: false
switch.loft_blind_stop_loft_suite_blind:
  name: "RB Stop"
  hidden: false
switch.loft_blind_open_loft_suite_blind:
  name: "RB Up"
  hidden: false
light.scenario_1_light:
  name: "AC On + Room Empty"
  hidden: false
light.scenario_2_light:
  name: "AC On + Door Open"
  hidden: false
light.scenario_3_light:
  name: "Turning AC On + Door Open"
  hidden: false
light.alexa_started_ac:
  name: "Quick Chill"
  hidden: false
binary_sensor.loft_pir_bedroom_door:
  name: "loftdoorcontact"
  hidden: false
input_boolean.ac_hi_lo_speed:
  name: "AC Fan Speed High"
  hidden: false
input_boolean.garden_d_cleared:
  name: "Garden D Cleared"
  hidden: false
script.oppy_mow_all:
  name: "Oppy"
  hidden: false