
# Use this file to store secrets like usernames and passwords.
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/
some_password: <redacted>
arlo_password: <redacted>
gen_un: <redacted>
dyson_pw: <redacted>
miele_id: <redacted>
miele_secret: <redacted>
owm_key: <redacted>
sdm_secret: <redacted>
sonoff_pw: <redacted>
wifi_ssid: <redacted>
wifi_password: <redacted>
tilepw: <redacted>
ota_password: <redacted>
